### ISSUE TITLE
To branch or not to branch?

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-role-archivematica-src#105]
This is a question related with #104 which is a big PR that introduces several changes to the role. Would it be a good thing to have multiple stable branches in this repository, like the [archivematica](https://github.com/artefactual/archivematica) repository? For example, creating a stable/1.5.x and a stable/1.6.x branch, so that the ansible role is paired to the target archivematica branch.
The reason for this is that we may be reaching a point where it may no longer be possible or practical to assure that changes introduced in the role will be backward compatible with older branches of archivematica.
(I found this approach is used for example in https://github.com/elastic/ansible-elasticsearch, there is a stable/2.x branch to deploy ES 2.x and a stable/5.x branch to deploy ES 5.x)

**Comment by hakamine** [comment]
Currently thinking of doing as follows:
* A new 'stable/1.6.x' branch will be created in this repo, to which PR #104 will be merged
* The 'stable/1.6.x' branch will eventually become the default branch (replacing the current master branch)
* The old 'master' branch will become 'stable/1.5.x'

**Comment by hakamine** [comment]
The stable/1.6.x has been created.
Before renaming the 'master' branch to 'stable/1.5.x', will create a PR in https://github.com/artefactual/deploy-pub that fixes the playbook in https://github.com/artefactual/deploy-pub/tree/master/playbooks/archivematica to use the newer stable/1.6.x branch

**Comment by sevein** [comment]
I like the idea, Héctor. Thanks!

**Comment by sevein** [comment]
One question: where is the virtualenv work for AM 1.7 going to live? That will will likely be backward incompatible. Do we need to create a qa/1.7.x branch?

**Comment by sevein** [comment]
Off the top of my head these are some things we need to take care of in this role for AM 1.7:
- Gunicorn asynchronous workers using gevent
- Gunicorn to use inotify reload engine
- Stop using /var/log/archivematica (rely on upstart/systemd)
- Stop serving static files from Nginx (WhiteNoise to be used in Dashboard/SS)
- Stop using git submodules: we'll likely be vendoring for now, maybe bower in the future?
- New environment variables like ALLOWED_HOSTS, GEARMAN_SERVER, ST_DB_URL, etc...
- Virtual environments

There's a lot more that we could do - but we definitely need a space (qa/1.7.x?) where we can start making these changes and I agree that having one "master" branch targeting every minor version of AM is unrealistic.

@jhsimpson - curious to hear your thoughts here. I don't think we need to make major releases of AM to accommodate these changes as I don't think we're making backward incompatible changes in public APIs. That said, if we need to call it AM 2.0 then let's do that - that's the least of my problems.

**Comment by hakamine** [comment]
Renamed 'master' branch to 'stable/1.5.x' and set 'stable/1.6.x' as the default branch for this repository.

**Comment by hakamine** [comment]
I think that creating a qa/1.7.x branch to include all the changes required to deploy AM 1.7 is a good idea. Should I go ahead and create one on top of the existing stable/1.6.x branch?

**Comment by sevein** [comment]
My point of view: :+1:

**Comment by sevein** [comment]
I've just created qa/1.7.x. I was deploying qa/1.x off stable/1.6.x and it felt... so wrong! :)
