### ISSUE TITLE
Make the automationtools repo configurable

### ISSUE THREAD

**Issue by lwo** [artefactual-labs/ansible-role-archivematica-src#131]
At the moment the repository is a constant:
https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/automation-tools.yml#L7

But we use a fork. Can you make it configurable, like:

repo:  "{{ archivematica_src_automationtools_repo }}"
?

**Comment by scollazo** [comment]
Added a new configuration value, "archivematica_src_automation_tools_repo"

**Comment by lwo** [comment]
Thanks.
