### ISSUE TITLE
File tasks break when archivematica_src_install_ss set to false

### ISSUE THREAD

**Issue by lwo** [artefactual-labs/ansible-role-archivematica-src#133]
When `archivematica_src_install_ss` is set to `false`, parent directories like:

/var/lib/archivematica
https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/ss-main.yml#L104

/etc/archivematica
https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/ss-main.yml#L127

and
/var/archivematica
https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/ss-main.yml#L119

are not created. Hence file operations further down the playbook break, as in:
https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/pipeline-websrv-gunicorn.yml#L19

https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/automation-tools.yml#L22

and
https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/pipeline-osconf.yml#L53

**Comment by scollazo** [comment]
Fixed in https://github.com/artefactual-labs/ansible-archivematica-src/pull/144
