### ISSUE TITLE
Log configuration and file missing for mcp-client and server

### ISSUE THREAD

**Issue by lwo** [artefactual-labs/ansible-role-archivematica-src#137]
In the qa/1.7 branch there is no longer a logfile placed in 
/var/log/archivematica/MCPServer/ 
/var/log/archivematica/MCPClient/

For the dashboard this was amendable via:
archivematica_src_am_dashboard_environment:
  SS_GUNICORN_ACCESSLOG: "/var/log/archivematica/storage-service/gunicorn.access_log"
  SS_GUNICORN_ERRORLOG: "/var/log/archivematica/storage-service/gunicorn.error_log"
  SS_GUNICORN_LOGLEVEL: "info"

But how to proceed for the MCP server and client?

**Comment by sevein** [comment]
Hi @lwo, if you're using 14.04 (upstart):

    $ sudo tail -f /var/log/upstart/archivematica-mcp-server.log
    $ sudo tail -f /var/log/upstart/archivematica-mcp-client.log 

Or if you're using 16.04 (systemd):

    $ sudo journalctl -f -u archivematica-mcp-server
    $ sudo journalctl -f -u archivematica-mcp-client

Please let me know if it works for you!

**Comment by lwo** [comment]
Yes, I see it there for upstart. Thanks.
