### ISSUE TITLE
clamav socket is not updated for fedora/rh hosts

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/ansible-role-archivematica-src#138]
It needs to be set to
clamav_server = /var/run/clamd.scan/clamd.sock

**Comment by sevein** [comment]
If you think an environment string is convenient, this is the one you could use:

`ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_SERVER=/var/run/clamd.scan/clamd.sock`

**Comment by scollazo** [comment]
Fixed in #185
