### ISSUE TITLE
clamdscan permission denied in fedora/centos

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/ansible-role-archivematica-src#139]
clamd@scan service in fedora, runs as clamscan user. We need to add that user to the archivematica group in order for it to be able to scan files in /var/archivematica

**Comment by sevein** [comment]
By default I think we're streaming the file (`clamav_pass_by_reference = False`). Maybe the issue is in that the archivematica user can't write to the socket?

**Comment by scollazo** [comment]
Fixed in #188 and artefactual-labs/ansible-clamav#6
