### ISSUE TITLE
clamdscan fails with big files

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/ansible-role-archivematica-src#140]
Not sure if due to the 10s timeout in archivematica, but using
clamav_pass_by_reference = True

it works

**Comment by sevein** [comment]
What's the error that you're seeing?

**Comment by sevein** [comment]
@scollazo this is going to be fixed as part of https://github.com/artefactual-labs/ansible-archivematica-src/issues/140. It'd still be nice if you added the error message that you saw. Not a high priority because it's mitigated with https://github.com/artefactual/archivematica/pull/772.

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual/archivematica/pull/772.

**Comment by nickwilkinson** [comment]
@scollazo can you please test this?

**Comment by scollazo** [comment]
This is fixed in archivematica and in the clamav role ( artefactual-labs/ansible-clamav#3 )
