### ISSUE TITLE
Problem: AM17 logging config isn't populated yet

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/ansible-role-archivematica-src#147]
Similar issue in am-packbuild (deb/rpm): https://github.com/artefactual-labs/am-packbuild/issues/63. It depends on https://github.com/artefactual/archivematica/pull/782 and https://github.com/artefactual/archivematica-storage-service/pull/256 (not merged yet when this issue was reported).

**Comment by mamedin** [comment]
Merged #167
