### ISSUE TITLE
Problem: no env vars for clamav config

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/ansible-role-archivematica-src#156]
On latest AM qa/1.x there are some settings for clamav:

ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_SERVER
ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_PASS_BY_REFERENCE
ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_TIMEOUT
ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_BACKEND
ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_MAX_FILE_SIZE
ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_MAX_SCAN_SIZE

These variables should be added to the templates and then, these env vars could be modified using the vars.yml file.

For example, for RH/CentOS, this could be added to the `/etc/sysconfig/archivematica-mcp-client` template.

**Comment by scollazo** [comment]
This can be done by addimt  the appropiate vars to the archivematica_src_am_mcpclient_environment list, as we iterate over those items here:

https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/templates/etc/sysconfig/archivematica-mcp-client.j2#L6

**Comment by mamedin** [comment]
Thank you Santi And Jesus, indeed that option already exists but I did not know.

I close the issue.
