### ISSUE TITLE
Problem: unable to update python-minimal in xenial

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/ansible-role-archivematica-src#178]
When the system packages are updated in xenial, python-minimal fails with:

<pre>
Setting up python-minimal (2.7.12-1~16.04) ...
dpkg: error processing package python-minimal (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 python-minimal
E: Sub-process /usr/bin/dpkg returned an error code (1)
</pre>

This seems related to https://bugs.launchpad.net/ubuntu/+source/python-defaults/+bug/1750586 ,  and I tested that removing the archivematica virtualenvs at /usr/share/python, fixes the problem and the package install ends well.

**Comment by scollazo** [comment]
@jhsimpson proposes /usr/share/archivematica/virtualenvs as path for the virtualenvs, I'll try to use it and look for side effects

**Comment by mamedin** [comment]
Fixed PR #182
