### ISSUE TITLE
Problem:  Missing easy way to deploy v1.7.0 of Archivematica

### ISSUE THREAD

**Issue by jhsimpson** [artefactual-labs/ansible-role-archivematica-src#191]
Now that there is an official v1.7.0 tag in Archivematica, we need a way to make sure that this repo has an easy way to install that version.

This could be done with a stable/1.7.x branch in this repo, and a v1.7.0 tag?

**Comment by scollazo** [comment]
:+1: , we should do the same in deploy-pub

**Comment by scollazo** [comment]
Created `stable/1.7.x` branch and v1.7.0 tag. Should we also rename qa/1.7.x into qa/1.x?
