### ISSUE TITLE
Problem: elasticsearch host and port can't be configured

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/ansible-role-archivematica-src#198]
It's harcoded to localhost:9200 in https://github.com/artefactual-labs/ansible-archivematica-src/blob/stable/1.7.x/defaults/main.yml#L73

**Comment by sevein** [comment]
Before #199, it was possible to pass the config attribute via the env
string dictionary right? What is exactly the advantage of the solution
introduced by #199?
