### ISSUE TITLE
Problem: Roles need updating for Sampledata PRs #38 #37

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/ansible-role-archivematica-src#208]
As we add to the `createtransfers.py` script, we need to update the role along the lines of:
https://github.com/artefactual-labs/ansible-archivematica-src/issues/180

PRs:

* https://github.com/artefactual/archivematica-sampledata/pull/38
* https://github.com/artefactual/archivematica-sampledata/pull/37 

This issue is contingent for now on whether/when they are merged.

**Comment by sevein** [comment]
@ross-spencer I've filed https://github.com/artefactual/archivematica-sampledata/pull/41 with a simpler build method that I think could be used in this role.

**Comment by ross-spencer** [comment]
**Main.yml**

https://github.com/artefactual-labs/ansible-archivematica-src/blob/167896e6798ef62a65610e62dade312d91d1534f/tasks/main.yml#L159-L178

**Redhat**

https://github.com/artefactual-labs/ansible-archivematica-src/blob/f7e8e918df67f1be7b07d8efc3e972dcdf7f169a/tasks/common-family-redhat.yml#L65-L71

To change these commands, I believe the following needs to be done (added to the redhat script, and changed in `main.yml`:
```
name: "Generate special sampledata transfers"
command: "~/archivematica-sampledata/createtransfers/make simple"
when: "archivematica_src_install_sample_data|bool"
become: "no"
```

**Comment by scollazo** [comment]
I'm not sure if we are using the common-family-redhat.yml, as I wasn't able to find where we load that file.
