### ISSUE TITLE
Problem: mysql database vars are needed by other roles

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/ansible-role-archivematica-src#210]
When creating a new instance, the database is created by the percona/mysql role, and uses the default values described in this role:

https://github.com/artefactual/deploy-pub/blob/master/playbooks/archivematica-xenial/vars-singlenode-1.7.yml#L33

In #204 , we went to far, and the mysql related vars needs to be brought back

**Comment by mamedin** [comment]
I agree with this commit , if we are going to use the default values ​​it is better not to have to add them to `vars.yml` file or use extra-vars.
