### ISSUE TITLE
Fixity cron job needs to support the SS using a MySQL db

### ISSUE THREAD

**Issue by amayita** [artefactual-labs/ansible-role-archivematica-src#348]
Hi,

According to:  https://wiki.archivematica.org/Archivematica_1.13.0_and_Storage_Service_0.18.0_release_notes#Archivematica_Storage_Service_now_uses_MySQL_by_default
"MySQL is now the default database in Archivematica Storage Service. **SQLite is still supported** but we encourage users to migrate. "

Since in am 1.13 we are supporting both SQLlite and MySQL for the SS database, the [fixity cron job](https://github.com/artefactual-labs/ansible-archivematica-src/blob/874948d6e14fbf56e190a82607f1cfd4426de667/templates/bin/fixity-cron) needs to be updated to support both. 
https://github.com/artefactual-labs/ansible-archivematica-src/blob/stable/1.13.x/templates/bin/fixity-cron

So we need a way to identify what DB we are using and provide a way to obtain the email addresses from the cron-job.

Thanks!

**Comment by mamedin** [comment]
We can use django dbshell that works with both databases.
