### ISSUE TITLE
Please add a dependency on ca-certificates

### ISSUE THREAD

**Issue by amayita** [artefactual-labs/ansible-role-archivematica-src#356]
If this package is not installed, apt fails for not trusting the ssl cert in archivematica.org:
(this is after changing to LE ssl cert in archivematica.org)

```
Err:12 https://packages.archivematica.org/1.9.x/ubuntu-externals bionic Release                          
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 68.183.194.240 443]
```
The fix is easy enough:
` apt install ca-certificates`

Thanks!

**Comment by mamedin** [comment]
The package has the same name in Ubuntu and CentOS, so we should add the dependency here:

https://github.com/artefactual-labs/ansible-archivematica-src/tree/qa/1.x/vars

(Debian.yml and RedHat.yml files, in `ansible_deps` list)

**Comment by amayita** [comment]
Fixed on qa/1.x and stable/1.13.x 
https://github.com/artefactual-labs/ansible-archivematica-src/commit/c3da8967554c4dcff9e851bd43aabea12f55986c
