### ISSUE TITLE
Make the installation developer friendlier 

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-role-archivematica-src#6]
Instead of copying from the /srv directory, create symlinks to it, so that changes can be easily tested and commited/pushed?

**Comment by sevein** [comment]
a51f1a8 makes things better, but we can probably study more options, e.g. auto-reloading, etc... I'll leave this open for now.

**Comment by hakamine** [comment]
Improvements mentioned above are already in the code. Closing.
