### ISSUE TITLE
change source of os dependencies based on am version

### ISSUE THREAD

**Issue by jhsimpson** [artefactual-labs/ansible-role-archivematica-src#64]
https://github.com/artefactual-labs/ansible-role-archivematica-src/blob/master/tasks/tear-up.yml#L17

In that line, the externals-dev ppa is added to the list of ubuntu trusted repos.

For qa releases, this is good, but for stable/1.4.x AM, the 1.4 ppa should be added instead.

For stable/1.5.x, the packages.archivematica.org repo for 1.5 should be added, instead of a ppa.

This line should probably change its behaviour depending on which version of AM is being installed.

**Comment by hakamine** [comment]
I think we still need to pull dependencies from externals-dev ppa, because the archivematica 1.5 repo does not have yet all the required package dependencies. AFAIK only the archivematica packages, fido and siegfried are there.

**Comment by jhsimpson** [comment]
You're right, not all the dependencies are in packages.archivematica.org yet.  But deciding which repo to use still depends on the branch being installed.  The installation instructions for 1.5 say to use  ppa:archivematica/externals, rather than externals-dev.  externals-dev could get changed, for qa/testing purposes and is therefore not reliable for doing releases based on a stable/ branch.  

We want to move more packages to packages.archivematica.org, on for the 1.6 release hopefully this will be completed.

**Comment by hakamine** [comment]
fixed in #77
