### ISSUE TITLE
Conver this repo into normal instead of fork

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/ansible-role-archivematica-src#69]
I wonder if we can ask GitHub to convert this repo into normal mode instead of fork mode (hakamine's repo is the parent). That would allow us to make searches, which is currently not possible as forks are not searchable?

**Comment by hakamine** [comment]
Would it solve the problem if I delete https://github.com/hakamine/ansible-role-archivematica-src ?

**Comment by sevein** [comment]
No idea! Maybe?

**Comment by hakamine** [comment]
deleted the parent repo

**Comment by sevein** [comment]
Wop! I think we fixed it! :)

**Comment by Hwesta** [comment]
https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/ Looks like when you delete a public repo, one of the forks is made primary.

You can also request a fork be detached, but I can't find the page.
