### ISSUE TITLE
Use packages.archivematica.org for dependencies

### ISSUE THREAD

**Issue by jhsimpson** [artefactual-labs/ansible-role-archivematica-src#74]
Currently this role is adding ppa:archivematica/externals-dev as a source, it should also be added packages.archivematica.org.  Probably should have the option to use ppa:archivematica/externals instead of externals-dev when doing a production install.  

The externals-dev ppa shows a warning on launchpad, and it appears that it is not working properly.  I noticed that in one test, I got siegfried 1.1.0 installed, when I should have been able to get 1.4.5 from externals-dev.  packages.archivematica.org/1.5.x has siegfried 1.5.0, which is the version that should be installed with Archivematica 1.5.0 and greater.

**Comment by hakamine** [comment]
fixed in #77
