### ISSUE TITLE
archivematica-storage-service/lib dir check not working properly  

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-role-archivematica-src#84]
It looks like the part of the role that checks for existence of archivematica-storage-service/lib is not working properly:
https://github.com/artefactual-labs/ansible-role-archivematica-src/blob/master/tasks/ss-main.yml#L88-L95 
When running the playbook in https://github.com/artefactual/deploy-pub/tree/master/playbooks/archivematica it is adding "--find-links lib" to pip  even though the lib directory doesn't exist

**Comment by jhsimpson** [comment]
This is working properly.  I reported the issue to hakamine, but discovered in re-testing that I was using an old copy of this role.  Doing ansible-galaxy -f -r requirements.yml and rerunning the playbook fixed the problem.

The set_fact step was not originally showing, now it is:

TASK: [archivematica-src | set_fact ] ***************************************** 
ok: [am-local]

TASK: [archivematica-src | set_fact ] ***************************************** 
skipping: [am-local]
